app/models.py
from datetime import datetime

from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app import db
from . import login_manager

class Post(db.Model):
    __tablename__ = 'posts'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(30), unique=True, nullable=False)
    body = db.Column(db.Text, nullable=False)
    pubdate = db.Column(db.DateTime, default=datetime.now, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __repr__(self):
        return f'post{self.id} - {self.title[:10]}'

class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(30), unique=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)
    posts = db.relationship('Post', backref='user')

    @property
    def password(self):
        raise AttributeError('Cant access this')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)
    
    def __repr__(self):
        return f'{self.username}'

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):

    title = StringField('Title', validators=[DataRequired()])
    body = TextAreaField('Body', validators=[DataRequired()])
    sumbit = SubmitField('Post')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_login import LoginManager

from config import option

login_manager = LoginManager()
login_manager.login_view = 'auth.login'
bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(env):
    
    app = Flask(__name__)
    app.config.from_object(option[env])

    db.init_app(app)

    from app.main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    from app.auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    login_manager.init_app(app)
    bootstrap.init_app(app)


    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, redirect
from flask_login import current_user, login_required

from app.main import main
from .forms import PostForm
from app.models import Post, User, db


@main.route('/')
@login_required
def index():
    posts = Post.query.all()[::-1]
    return render_template('index.html', posts=posts)

@main.route('/post', methods=['GET', 'POST'])
@login_required
def post():
    form = PostForm()

    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        post = Post(title=title,body=body, user=current_user)
        db.session.add(post)
        db.session.commit()
        return redirect('/')
    return render_template('post.html', form=form)

@main.route('/about')
@login_required
def about():
    posts = current_user.posts[::-1]
    return render_template('about.html', posts=posts)

app/templates/about.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron">
    <h1 class="display-4">About me</h1>
    <p class="lead">This is {{current_user}}</p>
    <hr class="my-4">
    <p>My Posts</p>
</div>

<div class="container home">
    {% if posts %}
       {% for post in posts%}
       <div class="containter post rounded-lg border-bottom">
          <h2 class="post-title">{{post.title}}</h2>
          <h4 class="post-body">{{post.body}}</h4>
          <h4 class="post-details">at {{post.pubdate.replace(microsecond=0)}} by {{post.user|capitalize}}</h4>
       </div>
       {%endfor%}
    {% else %}
    <div class="container">
       <h3>No posts</h3>
    </div>
    {% endif %} 
</div>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block styles %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<link rel="stylesheet" href="{{url_for('static', filename='style.css')}}" >
{% endblock %}


{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
   <a class="navbar-brand" href="/">Blogsite</a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse" id="navbarNav">
     <ul class="navbar-nav">
       <li class="nav-item active">
         <a class="nav-link" href="{{url_for('main.index')}}">Home <span class="sr-only">(current)</span></a>
       </li>
       <li class="nav-item">
         <a class="nav-link" href="{{ url_for('main.post')}}">Post</a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="{{ url_for('main.about')}}">About</a>
      </li>
     </ul>
   </div>
    {% if current_user.is_authenticated %}
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout')}}">Logout</a></li>
    </ul>
     {% else %}
      <ul class="nav navbar-nav navbar-right">
      <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.login')}}">Login</a></li>
      <li class="nav-item"><a class="nav-link my-2 my-sm-0" href="{{ url_for('auth.register')}}">Register</a></li>
      </ul>
     {% endif %}
 </nav>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
   <div class="container home">
   {% if posts %}
      {% for post in posts%}
      <div class="containter post rounded-lg border-bottom">
         <h2 class="post-title">{{post.title}}</h2>
         <h4 class="post-body">{{post.body}}</h4>
         <h4 class="post-details">at {{post.pubdate.replace(microsecond=0)}} by {{post.user|capitalize}}</h4>
      </div>
      {%endfor%}
   {% else %}
   <div class="container">
      <h3>No posts</h3>
   </div>
   {% endif %} 
   </div>

{% endblock %}

app/templates/post.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf%}

{% block content %}
<div class="post-form">
<form method='POST'>
    {{form.hidden_tag()}}
    <div class="form-group">
      <label for="title">Title</label>
      {{ form.title(id="title", class="form-control") }}
    </div>
    <div class="form-group">
      <label for="body">Body</label>
      {{ form.body(id="body", class="form-control")}}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock %}